"""
db.py — SQLite schema and connection helper.

This module owns ALL database concerns:
- Schema definitions (CREATE TABLE statements)
- Connection management (singleton, context-manager friendly)
- Schema initialization (idempotent CREATE IF NOT EXISTS + additive migrations)

It does NOT own:
- Business logic (that's app.py / compute.py)
- AI calls (that's classifier.py)
- Frontend formatting (that's the API layer)

Multi-tenant: every user-data table has a user_id column. Categories,
recurring_patterns, completions, adhoc_tasks, and settings are scoped
per-user. The `users` table is the root of identity.
"""
import os
import sqlite3
from contextlib import contextmanager
from pathlib import Path

# Production may set DB_PATH to a mounted volume (e.g. /var/data/academic.sqlite3).
# RAILWAY_VOLUME_MOUNT_PATH is injected automatically by Railway when a volume is attached.
_db_path_env = os.environ.get("DB_PATH", "").strip()
_vol_mount = os.environ.get("RAILWAY_VOLUME_MOUNT_PATH", "").strip()
DB_PATH = Path(
    _db_path_env or
    (f"{_vol_mount}/academic.sqlite3" if _vol_mount else "") or
    str(Path(__file__).parent / "academic.sqlite3")
)

# Schema for fresh DB initialization. Existing DBs are migrated additively in init_db().
SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id          INTEGER PRIMARY KEY,
    email       TEXT NOT NULL UNIQUE,
    google_sub  TEXT UNIQUE,            -- NULL until first OAuth login
    name        TEXT,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
    id                 INTEGER PRIMARY KEY,
    user_id            INTEGER NOT NULL,
    name               TEXT NOT NULL,
    department         TEXT,
    mandatory          BOOLEAN DEFAULT 0,
    color_dark         TEXT,
    color_mid          TEXT,
    color_light        TEXT,
    sort_order         INTEGER DEFAULT 0,
    -- Derived from user_context by AI on PUT /context. NULL = use kind default.
    default_importance INTEGER CHECK (default_importance BETWEEN 1 AND 5 OR default_importance IS NULL),
    default_urgency    INTEGER CHECK (default_urgency BETWEEN 1 AND 5 OR default_urgency IS NULL),
    -- User's self-rated knowledge for this course. NULL = not set.
    self_confidence    TEXT CHECK (self_confidence IN ('excellent','partial','gap') OR self_confidence IS NULL),
    gap_notes          TEXT,
    keywords           TEXT,   -- comma-separated; auto-generated by Gemini on course creation
    UNIQUE (user_id, name),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS recurring_patterns (
    id                  INTEGER PRIMARY KEY,
    user_id             INTEGER NOT NULL,
    category_id         INTEGER NOT NULL,
    kind                TEXT NOT NULL CHECK (kind IN ('lecture', 'tutorial', 'hw', 'reading')),
    day_of_week         TEXT,
    start_time          TEXT,
    end_time            TEXT,
    hw_release_day      TEXT,
    hw_release_time     TEXT,
    hw_due_offset_days  INTEGER,
    hw_due_time         TEXT,
    label               TEXT,
    weeks_active        TEXT DEFAULT '[1,2,3,4,5,6,7,8,9,10,11,12,13]',
    is_required         BOOLEAN DEFAULT 0,
    default_importance  INTEGER CHECK (default_importance BETWEEN 1 AND 5 OR default_importance IS NULL),
    default_urgency     INTEGER CHECK (default_urgency BETWEEN 1 AND 5 OR default_urgency IS NULL),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS completions (
    pattern_id       INTEGER NOT NULL,
    occurrence_date  DATE NOT NULL,
    user_id          INTEGER NOT NULL,
    status           TEXT CHECK (status IN ('done', 'skipped') OR status IS NULL),
    notes            TEXT,
    scheduled_at     DATETIME,
    importance       INTEGER CHECK (importance BETWEEN 1 AND 5 OR importance IS NULL),
    urgency          INTEGER CHECK (urgency BETWEEN 1 AND 5 OR urgency IS NULL),
    place            TEXT,
    updated_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pattern_id, occurrence_date),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (pattern_id) REFERENCES recurring_patterns(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS adhoc_tasks (
    id            INTEGER PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    category_id   INTEGER NOT NULL,
    title         TEXT NOT NULL,
    type          TEXT,
    place         TEXT,
    importance    INTEGER CHECK (importance BETWEEN 1 AND 5),
    urgency       INTEGER CHECK (urgency BETWEEN 1 AND 5),
    release_at    DATETIME,
    due_at        DATETIME,
    scheduled_at  DATETIME,
    notes         TEXT,
    status        TEXT DEFAULT 'open' CHECK (status IN ('open', 'done', 'skipped')),
    created_at    DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS settings (
    user_id  INTEGER NOT NULL,
    key      TEXT NOT NULL,
    value    TEXT,
    PRIMARY KEY (user_id, key),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback (
    id          INTEGER PRIMARY KEY,
    user_id     INTEGER NOT NULL,
    text        TEXT NOT NULL,
    page        TEXT,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

"""

# Indexes are created AFTER table migrations run, since some reference
# columns (user_id) added by the multi-tenancy migration.
INDEXES = """
CREATE INDEX IF NOT EXISTS idx_categories_user        ON categories(user_id);
CREATE INDEX IF NOT EXISTS idx_patterns_user          ON recurring_patterns(user_id);
CREATE INDEX IF NOT EXISTS idx_patterns_category      ON recurring_patterns(category_id);
CREATE INDEX IF NOT EXISTS idx_completions_date       ON completions(occurrence_date);
CREATE INDEX IF NOT EXISTS idx_completions_user_date  ON completions(user_id, occurrence_date);
CREATE INDEX IF NOT EXISTS idx_adhoc_status           ON adhoc_tasks(status);
CREATE INDEX IF NOT EXISTS idx_adhoc_release          ON adhoc_tasks(release_at);
CREATE INDEX IF NOT EXISTS idx_adhoc_user_status      ON adhoc_tasks(user_id, status);
CREATE INDEX IF NOT EXISTS idx_feedback_created       ON feedback(created_at DESC);
"""

# Pre-seeded "owner" user — Amit. Created on first init if no users exist.
# Anchors all existing data (which was created before multi-tenancy) to user 1.
OWNER_USER_ID = 1
OWNER_EMAIL = "amitsha1509@gmail.com"
OWNER_NAME = "Amit"


def init_db():
    """Idempotent — safe to call multiple times. Creates tables if missing,
    and additively migrates existing DBs that predate newer columns/tables.

    Migrations layered in order; each step is a no-op if already applied.

    SAFETY: disables FK enforcement during the migration. SQLite cascades
    deletes through ON DELETE CASCADE FKs when a parent table is dropped
    during a rebuild — even if you've recreated the parent with identical
    rows. Disabling FKs while rebuilding (the standard recommended pattern,
    https://sqlite.org/lang_altertable.html#otheralter) prevents that. We
    re-enable + run foreign_key_check at the end to verify integrity.
    """
    with connect() as conn:
        conn.execute("PRAGMA foreign_keys = OFF")
        conn.executescript(SCHEMA)

        # ─── Pre-seed the owner user FIRST ───────────────────────────────
        # Subsequent migrations backfill user_id = OWNER_USER_ID for existing
        # rows. Those backfills have FK constraints on users(id), so the user
        # row must already exist when they run.
        n_users = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        if n_users == 0:
            conn.execute(
                "INSERT INTO users(id, email, name) VALUES(?, ?, ?)",
                (OWNER_USER_ID, OWNER_EMAIL, OWNER_NAME)
            )

        # ─── Session 3 migration: pattern-level imp/urg defaults ────────
        existing = {r["name"] for r in conn.execute(
            "PRAGMA table_info(recurring_patterns)").fetchall()}
        if "default_importance" not in existing:
            conn.execute(
                "ALTER TABLE recurring_patterns ADD COLUMN default_importance "
                "INTEGER CHECK (default_importance BETWEEN 1 AND 5 OR default_importance IS NULL)"
            )
        if "default_urgency" not in existing:
            conn.execute(
                "ALTER TABLE recurring_patterns ADD COLUMN default_urgency "
                "INTEGER CHECK (default_urgency BETWEEN 1 AND 5 OR default_urgency IS NULL)"
            )

        # ─── Session 4 migration: multi-tenancy (user_id columns) ───────
        # Add user_id to existing user-data tables. Backfill all rows to user 1
        # (Amit, the original owner). Pattern works the same for every table.
        for table in ("categories", "recurring_patterns", "completions", "adhoc_tasks"):
            cols = {r["name"] for r in conn.execute(
                f"PRAGMA table_info({table})").fetchall()}
            if "user_id" not in cols:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN user_id INTEGER")
                conn.execute(f"UPDATE {table} SET user_id = ? WHERE user_id IS NULL",
                             (OWNER_USER_ID,))

        # Settings used `key` as the sole primary key. Rebuild with (user_id, key) PK.
        # Use the safe SQLite rebuild dance: create-temp → copy → drop-old → rename-temp.
        # See https://sqlite.org/lang_altertable.html — never RENAME the old table
        # before its children's FKs are pointed at the new one.
        settings_cols = {r["name"] for r in conn.execute(
            "PRAGMA table_info(settings)").fetchall()}
        if "user_id" not in settings_cols:
            conn.executescript("""
                CREATE TABLE settings_new (
                    user_id  INTEGER NOT NULL,
                    key      TEXT NOT NULL,
                    value    TEXT,
                    PRIMARY KEY (user_id, key),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                );
            """)
            conn.execute(
                "INSERT INTO settings_new(user_id, key, value) "
                "SELECT ?, key, value FROM settings",
                (OWNER_USER_ID,)
            )
            conn.executescript("""
                DROP TABLE settings;
                ALTER TABLE settings_new RENAME TO settings;
            """)

        # The `categories.name` field used to be globally UNIQUE. Per-user multi-
        # tenancy needs `(user_id, name)` UNIQUE instead. SQLite can't drop a
        # column constraint via ALTER, but the new SCHEMA above already declared
        # the right UNIQUE for a fresh DB. For an existing DB, the legacy global
        # UNIQUE on name still applies — meaning two different users couldn't
        # both create "כללי". We rebuild categories to fix this.
        cat_indexes = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='index' AND tbl_name='categories'"
        ).fetchall()
        legacy_unique = any(
            r["sql"] and "name" in r["sql"] and "user_id" not in r["sql"] and "UNIQUE" in r["sql"].upper()
            for r in cat_indexes
        )
        # Detect the auto-created sqlite_autoindex from the legacy `name TEXT NOT NULL UNIQUE`.
        # When present, the table's CREATE statement contains "UNIQUE" on name without user_id.
        cat_create = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name='categories'"
        ).fetchone()
        needs_categories_rebuild = (
            cat_create and cat_create["sql"]
            and "UNIQUE (user_id, name)" not in cat_create["sql"]
            and "user_id" in cat_create["sql"]  # only rebuild AFTER user_id was added
        )
        if needs_categories_rebuild:
            # Safe rebuild: create-temp → copy → drop-old → rename-temp-to-old.
            conn.executescript("""
                CREATE TABLE categories_new (
                    id                 INTEGER PRIMARY KEY,
                    user_id            INTEGER NOT NULL,
                    name               TEXT NOT NULL,
                    department         TEXT,
                    mandatory          BOOLEAN DEFAULT 0,
                    color_dark         TEXT,
                    color_mid          TEXT,
                    color_light        TEXT,
                    sort_order         INTEGER DEFAULT 0,
                    default_importance INTEGER CHECK (default_importance BETWEEN 1 AND 5 OR default_importance IS NULL),
                    default_urgency    INTEGER CHECK (default_urgency BETWEEN 1 AND 5 OR default_urgency IS NULL),
                    self_confidence    TEXT CHECK (self_confidence IN ('excellent','partial','gap') OR self_confidence IS NULL),
                    gap_notes          TEXT,
                    keywords           TEXT,
                    UNIQUE (user_id, name),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                );
            """)
            conn.execute("""
                INSERT INTO categories_new(id, user_id, name, department, mandatory,
                                           color_dark, color_mid, color_light, sort_order,
                                           default_importance, default_urgency,
                                           self_confidence, gap_notes, keywords)
                SELECT id, user_id, name, department, mandatory,
                       color_dark, color_mid, color_light, sort_order,
                       default_importance, default_urgency,
                       self_confidence, gap_notes,
                       CASE WHEN typeof(keywords) = 'null' THEN NULL ELSE keywords END
                  FROM categories
            """)
            conn.executescript("""
                DROP TABLE categories;
                ALTER TABLE categories_new RENAME TO categories;
            """)

        # ─── Session 6 migration: per-category keywords ─────────────────
        cat_cols = {r["name"] for r in conn.execute(
            "PRAGMA table_info(categories)").fetchall()}
        if "keywords" not in cat_cols:
            conn.execute("ALTER TABLE categories ADD COLUMN keywords TEXT")

        # Populate keywords for existing categories that have none yet,
        # using the hardcoded keyword dict (Amit's courses). New-user courses
        # generated via the UI will have keywords set at creation time by Gemini.
        import keyword_classifier as _kc
        for course_name, kw_list in _kc.KEYWORDS.items():
            conn.execute(
                "UPDATE categories SET keywords=? "
                "WHERE name=? AND (keywords IS NULL OR keywords='')",
                (",".join(kw_list), course_name),
            )

        # ─── Indexes (run AFTER migrations so user_id columns exist) ────
        conn.executescript(INDEXES)

        # ─── Re-enable FK enforcement + verify integrity ────────────────
        # If any rebuild left orphan rows we'd want to know NOW, before any
        # endpoint touches them. Raise loud on violations.
        violations = conn.execute("PRAGMA foreign_key_check").fetchall()
        if violations:
            details = [tuple(v) for v in violations]
            raise RuntimeError(f"Migration produced FK violations: {details[:5]}... (n={len(details)})")
        conn.execute("PRAGMA foreign_keys = ON")


@contextmanager
def connect():
    """Context-managed sqlite connection with foreign keys + Row factory."""
    conn = sqlite3.connect(DB_PATH, detect_types=sqlite3.PARSE_DECLTYPES)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield conn
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def reset_db():
    """DESTRUCTIVE — drops everything and recreates. Used by seed.py."""
    ALLOWED_TABLES = {"feedback", "completions", "adhoc_tasks", "recurring_patterns",
                       "categories", "settings", "users"}
    with connect() as conn:
        for table in ALLOWED_TABLES:
            assert table.replace("_", "").isalnum(), f"unsafe table name: {table}"
            conn.execute(f"DROP TABLE IF EXISTS {table}")
        conn.executescript(SCHEMA)
        conn.executescript(INDEXES)


if __name__ == "__main__":
    init_db()
    print(f"Initialized DB at {DB_PATH}")
